name: place_prep
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  mark922_flutter_lottie: ^0.2.5
  residemenu: ^1.3.5
  share: ^0.6.5+4
  url_launcher: ^5.7.8
  carousel_pro: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/students-cap.png"

flutter:

  uses-material-design: true

  assets:
     - assets/images/download.jpg
     - assets/images/background.jpg
     - assets/images/icon.png
     - assets/images/card1.png
     - assets/images/capture.png
     - assets/images/students-cap.png
     - assets/images/card2.png
     - assets/images/card3.png
     - assets/images/card4.png
     - assets/local.json
     - assets/confetti.json
  
  fonts:
    - family: Acme
      fonts:
        - asset:  assets/font/Acme-Regular.ttf
          weight: 600
    - family: Josefin Sans
      fonts:
        - asset: assets/font/JosefinSans-Regular.ttf 
          weight: 200    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
