name: place_prep
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  mark922_flutter_lottie: ^0.2.5
  font_awesome_flutter: ^8.5.0
  residemenu: ^1.3.5
  share: ^0.6.5+4
  url_launcher: ^5.7.8
  carousel_pro: ^1.0.0
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.12.9+6
  google_sign_in: ^4.1.1
  intl_phone_number_input: ^0.2.0
  flare_splash_screen:
  splashscreen:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/students-cap.png"

flutter:

  uses-material-design: true

  assets:
    - assets/flare/splashIntro.flr
    - assets/images/
    - assets/local.json
    - assets/confetti.json
  
  fonts:
    - family: Acme
      fonts:
        - asset:  assets/font/Acme-Regular.ttf
          weight: 600
    - family: Josefin Sans
      fonts:
        - asset: assets/font/JosefinSans-Regular.ttf 
          weight: 200    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
